parameters:

#    tenolo_translation.form_type.entities.domain.class: Tenolo\Bundle\TranslationBundle\Form\Type\Entities\DomainEntityType

services:

#    tenolo_translation.form_type.entities.domain:
#        class: %tenolo_translation.form_type.entities.domain.class%
#        tags:
#            - { name: form.type }
