parameters:
    tenolo_translation.menu_builder_listener.class: Tenolo\Bundle\TranslationBundle\EventListener\MenuStructureListener
    tenolo_translation.service.class: Tenolo\Bundle\TranslationBundle\Service\TranslationService
    tenolo_translation.database_loader.class: Tenolo\Bundle\TranslationBundle\Translation\Loader\DatabaseLoader

services:

    tenolo_translation.menu_builder_listener:
        class: %tenolo_translation.menu_builder_listener.class%
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_listener, event: tenolo_menu.builder.build, method: onMenuBuilder }

    tenolo_translation.service:
        class: %tenolo_translation.service.class%
        arguments: ["@service_container"]

    tenolo_translation.database_loader:
        class: %tenolo_translation.database_loader.class%
        arguments: ["@service_container"]
        tags:
            - { name: translation.loader, alias: db }
