parameters:
    tenolo_translation.service.class: Tenolo\Bundle\TranslationBundle\Service\TranslationService
    tenolo_translation.database_loader.class: Tenolo\Bundle\TranslationBundle\Translation\Loader\DatabaseLoader
    tenolo_translation.twig_template_event.event.admin.class: Tenolo\Bundle\TranslationBundle\EventListener\TwigTemplateEventListener

services:
    tenolo_translation.service:
        class: %tenolo_translation.service.class%
        arguments: ["@service_container"]

    tenolo_translation.database_loader:
        class: %tenolo_translation.database_loader.class%
        arguments: ["@service_container"]
        tags:
            - { name: translation.loader, alias: db }

    # twig events
    tenolo_translation.twig_template_event.event.admin:
        class: %tenolo_translation.twig_template_event.event.admin.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: twig.template.event, method: onTemplateEvent }