services:
    tenolo_translation.form_type.entities.domain:
        class: Tenolo\Bundle\TranslationBundle\Form\Type\Entities\DomainEntityType
        tags:
            - { name: form.type, alias: tenolo_translation_domain_entity }

    tenolo_translation.form_type.entities.language:
        class: Tenolo\Bundle\TranslationBundle\Form\Type\Entities\LanguageEntityType
        tags:
            - { name: form.type, alias: tenolo_translation_language_entity }

    tenolo_translation.form_type.entities.token:
        class: Tenolo\Bundle\TranslationBundle\Form\Type\Entities\TokenEntityType
        tags:
            - { name: form.type, alias: tenolo_translation_token_entity }

    tenolo_translation.form_type.entities.translation:
        class: Tenolo\Bundle\TranslationBundle\Form\Type\Entities\TranslationEntityType
        tags:
            - { name: form.type, alias: tenolo_translation_translation_entity }
