parameters:

    # target entity resolver
    tenolo_translation.target_entity_resolver.domain.class: Tenolo\Bundle\TranslationBundle\Entity\Domain
    tenolo_translation.target_entity_resolver.language.class: Tenolo\Bundle\TranslationBundle\Entity\Language
    tenolo_translation.target_entity_resolver.token.class: Tenolo\Bundle\TranslationBundle\Entity\Token
    tenolo_translation.target_entity_resolver.translation.class: Tenolo\Bundle\TranslationBundle\Entity\Translation

    # entities
    tenolo_translation.entity.domain.class: %tenolo_translation.target_entity_resolver.domain.class%
    tenolo_translation.entity.language.class: %tenolo_translation.target_entity_resolver.language.class%
    tenolo_translation.entity.token.class: %tenolo_translation.target_entity_resolver.token.class%
    tenolo_translation.entity.translation.class: %tenolo_translation.target_entity_resolver.translation.class%

    # repositories
    tenolo_translation.repository.domain.class: %tenolo_core.default_repository.class%
    tenolo_translation.repository.language.class: %tenolo_core.default_repository.class%
    tenolo_translation.repository.token.class: %tenolo_core.default_repository.class%
    tenolo_translation.repository.translation.class: Tenolo\Bundle\TranslationBundle\Repository\TranslationRepository

services:

    tenolo_translation.repository.domain:
        class: %tenolo_translation.repository.domain.class%
        tags:
            -  { name: doctrine.repository, class: %tenolo_translation.entity.domain.class%, alias: translation_domain_repository }

    tenolo_translation.repository.language:
        class: %tenolo_translation.repository.language.class%
        tags:
            -  { name: doctrine.repository, class: %tenolo_translation.entity.language.class%, alias: translation_language_repository }

    tenolo_translation.repository.token:
        class: %tenolo_translation.repository.token.class%
        tags:
            -  { name: doctrine.repository, class: %tenolo_translation.entity.token.class%, alias: translation_token_repository }

    tenolo_translation.repository.translation:
        class: %tenolo_translation.repository.translation.class%
        tags:
            -  { name: doctrine.repository, class: %tenolo_translation.entity.translation.class%, alias: translation_repository }
