parameters:

    # entity
    tenolo_translation.entity.domain.class: Tenolo\Bundle\TranslationBundle\Entity\Domain
    tenolo_translation.entity.language.class: Tenolo\Bundle\TranslationBundle\Entity\Language
    tenolo_translation.entity.token.class: Tenolo\Bundle\TranslationBundle\Entity\Token
    tenolo_translation.entity.translation.class: Tenolo\Bundle\TranslationBundle\Entity\Translation

    # target entity resolver
    tenolo_translation.target_entity_resolver.domain.class: Tenolo\Bundle\TranslationBundle\Entity\Domain
    tenolo_translation.target_entity_resolver.language.class: Tenolo\Bundle\TranslationBundle\Entity\Language
    tenolo_translation.target_entity_resolver.token.class: Tenolo\Bundle\TranslationBundle\Entity\Token
    tenolo_translation.target_entity_resolver.translation.class: Tenolo\Bundle\TranslationBundle\Entity\Translation

services:
