services:

    tenolo_translation.service:
        class: Tenolo\Bundle\TranslationBundle\Service\TranslationService
        public: true
        arguments:
            - '@kernel'
            - '@doctrine'

    tenolo_translation.database_loader:
        class: Tenolo\Bundle\TranslationBundle\Translation\Loader\DatabaseLoader
        arguments:
            - "@doctrine"
        tags:
            - { name: translation.loader, alias: db }

    tenolo_translation.event_listener.renew_translation_cache:
        class: Tenolo\Bundle\TranslationBundle\EventListener\RenewTranslationCacheListener
        arguments:
            - '@tenolo_translation.service'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    tenolo_translation.command.renew:
        class: Tenolo\Bundle\TranslationBundle\Command\RenewCommand
        arguments:
            - '@tenolo_translation.service'
        tags:
            - { name: console.command }
